### PR TITLE
Add Romanian Readme

### PR DESCRIPTION
**Pull request by BootVirtual**
I've gone ahead and made the Romanian translation of the readme. (Issue #44) Let me know if there is anything more to do!

### CODE REVIEW

**Comment by FireCubeStudios** [comment]
The download link badge looks broken. It should look like this from the english readme. 
image

**Comment by BootVirtual** [comment]
Oops... must've messed up there. I'll fix it asap.

**Comment by BootVirtual** [comment]
It seems like there is no badge for Romanian so I went ahead and made it just a hyperlink. (Similar to the German readme)

**Comment by FireCubeStudios** [comment]
Looks good. Thanks!

**Pull request merged**
