### PR TITLE
Improved Placement of Copyright Logo and added discussion Link

### PR DESCRIPTION
**Pull request by PeritusDeveloper**
**Issue #47**

### Changes
- Improved Placement of Copyright Logo and MIT License in README.md
- Improved Placement of Copyright Logo and MIT License in [Readme_German.md](https://github.com/PeritusDeveloper/Protecc/blob/master/Readme/Readme_German.md)
- Improved Placement of Copyright Logo and corrected the dead links of MIT License in [Readme_hindi.md](https://github.com/PeritusDeveloper/Protecc/blob/master/Readme/readme_hindi.md)
- Changed name of Hindi Readme to match the convention of others.

### CODE REVIEW

**Comment by FireCubeStudios** [comment]
While we are at it. can you change the name of "assets" folder to be capitalized to "Assets", move the README.zh-CN.md into the folder with rest of readmes, add the changes to the zh-CN since it was forgotten and finally instead of linking to discussions it should link to the discord server

**Comment by PeritusDeveloper** [comment]
I will do these

**Comment by PeritusDeveloper** [comment]
I have updated the above asked things plus I observed that image links were wrong so I updated those too
Please review @FireCubeStudios

**Comment by FireCubeStudios** [comment]
Nice changes

**Comment by FireCubeStudios** [comment]
There is one conflicting file. Can you pull the changes made in the russian readme by #59 and add your improvements

**Comment by PeritusDeveloper** [comment]
Please review @FireCubeStudios

**Comment by FireCubeStudios** [comment]
Merging

**Pull request merged**
