### PR TITLE
Added Contributing.md

### PR DESCRIPTION
**Pull request by Mitternachtsmond**
**Issue #46**

### Changes

- Added **Contributing.md** with all the Instructions for new contributors
- Hyperlinked the links in CODE_OF_CONDUCT for better view.

### CODE REVIEW

**Comment by FireCubeStudios** [comment]
We should also include the details in readme and other prerequisites for code specific contributions

**Comment by Mitternachtsmond** [comment]
I looked around but did not find those parts so I did not wanted to write something wrong

**Comment by Mitternachtsmond** [comment]
What more is required in the file?

**Comment by FireCubeStudios** [comment]
I will add later some more details. Is this PR for hacktoberfest?

**Comment by Mitternachtsmond** [comment]
Actually Yes [😅](https://emojipedia.org/grinning-face-with-sweat/)

**Comment by FireCubeStudios** [comment]
Ok i guess there should be contact section to discord server then I will merge this

**Pull request merged**
